name: SpontaneousDiscord
main: spontanicus.SpontaneousDiscord
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: 0.5
description: Operates a discord bot as a minecraft plugin.
author: Spontanicus
api-version: 1.13
libraries:
  - net.dv8tion:JDA:5.0.0-alpha.10
  - club.minnced:discord-webhooks:0.8.0
  - com.google.guava:guava:31.1-jre